pages_pages:
    resource: "@PagesBundle/Controller/PagesController.php"
    type:     annotation

pages_pages:
    resource: "@PagesBundle/Controller/PagesController.php"
    type:     annotation

utilisateurs:
    resource: "@UtilisateursBundle/Controller/"
    type:     annotation
    prefix:   /

pages:
    resource: "@PagesBundle/Controller/"
    type:     annotation
    prefix:   /

ecommerce:
    resource: "@EcommerceBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"