# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    
    setNewFacture:
        class: EcommerceBundle\Services\GetFacture
        arguments: ["@service_container", '@templating']
    
    setNewReference:
        class: EcommerceBundle\Services\GetReference
        arguments: ["@security.context", "@doctrine.orm.entity_manager"]
        
    tva:
        class: EcommerceBundle\Twig\Extension\TvaExtension
        tags:
            - { name: twig.extension}
            
    montantTva:
        class: EcommerceBundle\Twig\Extension\MontantTvaExtension
        tags:
            - { name: twig.extension}
            
    redirectionListener:
        class: EcommerceBundle\Listener\Redirection
        arguments: ["@service_container", "@session"]
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}
            
            
    app.form.profile:
        class: UtilisateursBundle\Form\ProfileFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: fos_user_profile }     
            
    app.form.changePassword:
        class: UtilisateursBundle\Form\ChangePasswordFormType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: fos_user_change_password }