services:
#    ecommerce.example:
#        class: EcommerceBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    tva: 
        class: EcommerceBundle\Twig\Extension\TvaExtension
        tags:
            - {name: twig.extension}